### ISSUE TITLE
The compiled binary contains lot of test data

### ISSUE THREAD

**Issue by ahmad-kemsan** [andybalholm/brotli#27]
Issue description

On static analysis of the binary, generated after compiling our go fiber app we found out a lot of text and links in the final binary, which turned out to be test data in the package.

Please check this issue:

https://github.com/gofiber/fiber/issues/1782

**Comment by ahmad-kemsan** [comment]
Can't we use [grable](https://github.com/burrowers/garble) to replace those words with some base64 hashes? As these dictionary words contain some `https://` many of our customers on scanning find some suspicious flags.

**Comment by andybalholm** [comment]
I'm not really familiar with garble, but if I were doing a security scan of an executable, I'd be much more concerned by finding that the executable was obfuscated than by finding a few URLs in it.

If all you need to do is compress brotli (never decompress it), you could use github.com/andybalholm/pack/brotli. It's a simpler library that does brotli compression without using the static dictionary. But since this is a dependency of a dependency, that might not be an option.

**Comment by ahmad-kemsan** [comment]
Thanks for your help!
